In [1]:
import os
import pandas as pd
from pathlib import Path

In [2]:
PROJECT_ROOT = Path(os.getenv("PROJECT_ROOT"))

In [3]:
df = pd.read_csv(PROJECT_ROOT / "data/intermediate/data_all.csv")
df

,year,month,voivodeship,temperature,rainfall,humidity,population_density,population,vehicles_count,roads_length,incidents
0,2018,1,małopolskie,-1.149677,17.7,89.855484,224.0,3400.58,2565658,31444.0,2879
1,2018,2,małopolskie,-2.167143,20.0,92.866429,224.0,3400.58,2565658,31444.0,2658
2,2018,3,małopolskie,-0.725484,14.9,87.644194,224.0,3400.58,2565658,31444.0,2741
3,2018,4,małopolskie,10.383333,17.7,72.174667,224.0,3400.58,2565658,31444.0,2848
4,2018,5,małopolskie,17.081613,102.7,77.249677,224.0,3400.58,2565658,31444.0,2909
...,...,...,...,...,...,...,...,...,...,...,...
924,2022,8,podlaskie,21.509677,11.5,78.806452,56.6,1143.36,1019975,27452.3,1013
925,2022,9,podlaskie,10.533333,85.2,91.133333,56.6,1143.36,1019975,27452.3,947
926,2022,10,podlaskie,7.632258,45.3,94.612903,56.6,1143.36,1019975,27452.3,910
927,2022,11,podlaskie,1.273333,21.4,93.933333,56.6,1143.36,1019975,27452.3,941
928,2022,12,podlaskie,-2.141935,41.1,91.838710,56.6,1143.36,1019975,27452.3,1047

In [4]:
def min_max_scale(column):
    min_val = column.min()
    max_val = column.max()
    return (column - min_val) / (max_val - min_val)

In [5]:
numeric_columns = ['temperature', 'rainfall', 'humidity', 'population_density', 'population', 'vehicles_count', 'roads_length']

for column in numeric_columns:
    df[column] = min_max_scale(df[column])

df

,year,month,voivodeship,temperature,rainfall,humidity,population_density,population,vehicles_count,roads_length,incidents
0,2018,1,małopolskie,0.213086,0.063057,0.791341,0.538412,0.537277,0.365848,0.463839,2879
1,2018,2,małopolskie,0.182350,0.071250,0.866689,0.538412,0.537277,0.365848,0.463839,2658
2,2018,3,małopolskie,0.225900,0.053082,0.736004,0.538412,0.537277,0.365848,0.463839,2741
3,2018,4,małopolskie,0.561477,0.063057,0.348880,0.538412,0.537277,0.365848,0.463839,2848
4,2018,5,małopolskie,0.763820,0.365871,0.475882,0.538412,0.537277,0.365848,0.463839,2909
...,...,...,...,...,...,...,...,...,...,...,...
924,2022,8,podlaskie,0.897584,0.040969,0.514840,0.000321,0.043915,0.043102,0.376005,1013
925,2022,9,podlaskie,0.566009,0.303527,0.823319,0.000321,0.043915,0.043102,0.376005,947
926,2022,10,podlaskie,0.478372,0.161382,0.910395,0.000321,0.043915,0.043102,0.376005,910
927,2022,11,podlaskie,0.286280,0.076238,0.893389,0.000321,0.043915,0.043102,0.376005,941
928,2022,12,podlaskie,0.183111,0.146420,0.840971,0.000321,0.043915,0.043102,0.376005,1047

In [6]:
df.to_csv(PROJECT_ROOT / "data/intermediate/data_all_norm.csv", index=False)